In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [2]:
data = pd.read_csv("my_movies.csv")
data

              V1             V2             V3          V4     V5  ...  LOTR2  Harry Potter2  LOTR  Braveheart  Green Mile
0    Sixth Sense          LOTR1  Harry Potter1  Green Mile  LOTR2  ...      1              0     0           0           1
1      Gladiator        Patriot     Braveheart         NaN    NaN  ...      0              0     0           1           0
2          LOTR1          LOTR2            NaN         NaN    NaN  ...      1              0     0           0           0
3      Gladiator        Patriot    Sixth Sense         NaN    NaN  ...      0              0     0           0           0
4      Gladiator        Patriot    Sixth Sense         NaN    NaN  ...      0              0     0           0           0
5      Gladiator        Patriot    Sixth Sense         NaN    NaN  ...      0              0     0           0           0
6  Harry Potter1  Harry Potter2            NaN         NaN    NaN  ...      0              1     0           0           0
7      Gladiator        Patriot            NaN         NaN    NaN  ...      0              0     0           0           0
8      Gladiator        Patriot    Sixth Sense         NaN    NaN  ...      0              0     0           0           0
9    Sixth Sense           LOTR      Gladiator  Green Mile    NaN  ...      0              0     1           0           1

[10 rows x 15 columns]

In [5]:
data = data.iloc[:,5:]

# Apriori Algorithm

In [6]:
frequent_itemsets = apriori(data, min_support=0.1, use_colnames=True)
frequent_itemsets

C:\Users\user\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                                           itemsets
0       0.6                                      (Sixth Sense)
1       0.7                                        (Gladiator)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
4       0.6                                          (Patriot)
5       0.2                                            (LOTR2)
6       0.1                                    (Harry Potter2)
7       0.1                                             (LOTR)
8       0.1                                       (Braveheart)
9       0.2                                       (Green Mile)
10      0.5                           (Sixth Sense, Gladiator)
11      0.1                               (LOTR1, Sixth Sense)
12      0.1                       (Sixth Sense, Harry Potter1)
13      0.4                             (Sixth Sense, Patriot)
14      0.1                               (LOTR2, Sixth Sense)
15      0.1                                (Sixth Sense, LOTR)
16      0.2                          (Green Mile, Sixth Sense)
17      0.6                               (Patriot, Gladiator)
18      0.1                                  (Gladiator, LOTR)
19      0.1                            (Braveheart, Gladiator)
20      0.1                            (Green Mile, Gladiator)
21      0.1                             (LOTR1, Harry Potter1)
22      0.2                                     (LOTR1, LOTR2)
23      0.1                                (Green Mile, LOTR1)
24      0.1                             (LOTR2, Harry Potter1)
25      0.1                     (Harry Potter2, Harry Potter1)
26      0.1                        (Green Mile, Harry Potter1)
27      0.1                              (Braveheart, Patriot)
28      0.1                                (Green Mile, LOTR2)
29      0.1                                 (Green Mile, LOTR)
30      0.4                  (Sixth Sense, Gladiator, Patriot)
31      0.1                     (Sixth Sense, Gladiator, LOTR)
32      0.1               (Green Mile, Sixth Sense, Gladiator)
33      0.1                (LOTR1, Sixth Sense, Harry Potter1)
34      0.1                        (LOTR1, Sixth Sense, LOTR2)
35      0.1                   (Green Mile, Sixth Sense, LOTR1)
36      0.1                (LOTR2, Sixth Sense, Harry Potter1)
37      0.1           (Green Mile, Sixth Sense, Harry Potter1)
38      0.1                   (Green Mile, Sixth Sense, LOTR2)
39      0.1                    (Green Mile, Sixth Sense, LOTR)
40      0.1                   (Braveheart, Patriot, Gladiator)
41      0.1                      (Green Mile, Gladiator, LOTR)
42      0.1                      (LOTR1, LOTR2, Harry Potter1)
43      0.1                 (Green Mile, LOTR1, Harry Potter1)
44      0.1                         (Green Mile, LOTR1, LOTR2)
45      0.1                 (Green Mile, LOTR2, Harry Potter1)
46      0.1         (Green Mile, Sixth Sense, Gladiator, LOTR)
47      0.1         (LOTR1, Sixth Sense, LOTR2, Harry Potter1)
48      0.1    (Green Mile, Sixth Sense, LOTR1, Harry Potter1)
49      0.1            (Green Mile, Sixth Sense, LOTR1, LOTR2)
50      0.1    (Green Mile, Sixth Sense, LOTR2, Harry Potter1)
51      0.1          (Green Mile, LOTR1, LOTR2, Harry Potter1)
52      0.1  (Green Mile, Harry Potter1, LOTR1, Sixth Sense...

In [7]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules
rules.sort_values('lift',ascending = False).head(10)

                            antecedents                   consequents  ...  conviction  zhangs_metric
169                 (Green Mile, LOTR1)  (Sixth Sense, Harry Potter1)  ...         inf            1.0
227  (Green Mile, LOTR2, Harry Potter1)          (LOTR1, Sixth Sense)  ...         inf            1.0
159              (LOTR2, Harry Potter1)          (LOTR1, Sixth Sense)  ...         inf            1.0
183                 (Green Mile, LOTR1)          (LOTR2, Sixth Sense)  ...         inf            1.0
184                 (Green Mile, LOTR2)          (LOTR1, Sixth Sense)  ...         inf            1.0
185                (LOTR1, Sixth Sense)           (Green Mile, LOTR2)  ...         inf            1.0
215              (LOTR2, Harry Potter1)           (Green Mile, LOTR1)  ...         inf            1.0
214              (LOTR1, Harry Potter1)           (Green Mile, LOTR2)  ...         inf            1.0
186                (LOTR2, Sixth Sense)           (Green Mile, LOTR1)  ...         inf            1.0
157                (LOTR2, Sixth Sense)        (LOTR1, Harry Potter1)  ...         inf            1.0

[10 rows x 10 columns]

In [9]:
rules.shape

(250, 10)

In [10]:
rules[rules.lift>1]

         antecedents                                      consequents  ...  conviction  zhangs_metric
0      (Sixth Sense)                                      (Gladiator)  ...        1.80       0.400000
1        (Gladiator)                                    (Sixth Sense)  ...        1.40       0.533333
6      (Sixth Sense)                                        (Patriot)  ...        1.20       0.250000
7          (Patriot)                                    (Sixth Sense)  ...        1.20       0.250000
10     (Sixth Sense)                                           (LOTR)  ...        1.08       1.000000
..               ...                                              ...  ...         ...            ...
245     (Green Mile)       (LOTR1, Sixth Sense, LOTR2, Harry Potter1)  ...        1.80       1.000000
246  (Harry Potter1)          (Green Mile, LOTR1, Sixth Sense, LOTR2)  ...        1.80       1.000000
247          (LOTR1)  (Green Mile, Sixth Sense, LOTR2, Harry Potter1)  ...        1.80       1.000000
248    (Sixth Sense)        (Green Mile, LOTR1, LOTR2, Harry Potter1)  ...        1.08       1.000000
249          (LOTR2)  (Green Mile, LOTR1, Sixth Sense, Harry Potter1)  ...        1.80       1.000000

[236 rows x 10 columns]

#Try different values of support and confidence

In [11]:
import warnings
warnings.filterwarnings("ignore")
frequent_itemsets1 = apriori(data, min_support=0.2, use_colnames=True)
frequent_itemsets1

    support                           itemsets
0       0.6                      (Sixth Sense)
1       0.7                        (Gladiator)
2       0.2                            (LOTR1)
3       0.2                    (Harry Potter1)
4       0.6                          (Patriot)
5       0.2                            (LOTR2)
6       0.2                       (Green Mile)
7       0.5           (Sixth Sense, Gladiator)
8       0.4             (Sixth Sense, Patriot)
9       0.2          (Green Mile, Sixth Sense)
10      0.6               (Patriot, Gladiator)
11      0.2                     (LOTR1, LOTR2)
12      0.4  (Sixth Sense, Gladiator, Patriot)

In [12]:
rules1 = association_rules(frequent_itemsets1, metric="lift", min_threshold=0.6)
rules1

                 antecedents               consequents  antecedent support  ...  leverage  conviction  zhangs_metric
0              (Sixth Sense)               (Gladiator)                 0.6  ...      0.08         1.8       0.400000
1                (Gladiator)             (Sixth Sense)                 0.7  ...      0.08         1.4       0.533333
2              (Sixth Sense)                 (Patriot)                 0.6  ...      0.04         1.2       0.250000
3                  (Patriot)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
4               (Green Mile)             (Sixth Sense)                 0.2  ...      0.08         inf       0.500000
5              (Sixth Sense)              (Green Mile)                 0.6  ...      0.08         1.2       1.000000
6                  (Patriot)               (Gladiator)                 0.6  ...      0.18         inf       0.750000
7                (Gladiator)                 (Patriot)                 0.7  ...      0.18         2.8       1.000000
8                    (LOTR1)                   (LOTR2)                 0.2  ...      0.16         inf       1.000000
9                    (LOTR2)                   (LOTR1)                 0.2  ...      0.16         inf       1.000000
10  (Sixth Sense, Gladiator)                 (Patriot)                 0.5  ...      0.10         2.0       0.500000
11    (Sixth Sense, Patriot)               (Gladiator)                 0.4  ...      0.12         inf       0.500000
12      (Patriot, Gladiator)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
13             (Sixth Sense)      (Patriot, Gladiator)                 0.6  ...      0.04         1.2       0.250000
14               (Gladiator)    (Sixth Sense, Patriot)                 0.7  ...      0.12         1.4       1.000000
15                 (Patriot)  (Sixth Sense, Gladiator)                 0.6  ...      0.10         1.5       0.625000

[16 rows x 10 columns]

In [13]:
frequent_itemsets2 = apriori(data, min_support=0.3, use_colnames=True)
frequent_itemsets2

   support                           itemsets
0      0.6                      (Sixth Sense)
1      0.7                        (Gladiator)
2      0.6                          (Patriot)
3      0.5           (Sixth Sense, Gladiator)
4      0.4             (Sixth Sense, Patriot)
5      0.6               (Patriot, Gladiator)
6      0.4  (Sixth Sense, Gladiator, Patriot)

In [14]:
rules2 = association_rules(frequent_itemsets2, metric="lift", min_threshold=0.5)
rules2

                 antecedents               consequents  antecedent support  ...  leverage  conviction  zhangs_metric
0              (Sixth Sense)               (Gladiator)                 0.6  ...      0.08         1.8       0.400000
1                (Gladiator)             (Sixth Sense)                 0.7  ...      0.08         1.4       0.533333
2              (Sixth Sense)                 (Patriot)                 0.6  ...      0.04         1.2       0.250000
3                  (Patriot)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
4                  (Patriot)               (Gladiator)                 0.6  ...      0.18         inf       0.750000
5                (Gladiator)                 (Patriot)                 0.7  ...      0.18         2.8       1.000000
6   (Sixth Sense, Gladiator)                 (Patriot)                 0.5  ...      0.10         2.0       0.500000
7     (Sixth Sense, Patriot)               (Gladiator)                 0.4  ...      0.12         inf       0.500000
8       (Patriot, Gladiator)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
9              (Sixth Sense)      (Patriot, Gladiator)                 0.6  ...      0.04         1.2       0.250000
10               (Gladiator)    (Sixth Sense, Patriot)                 0.7  ...      0.12         1.4       1.000000
11                 (Patriot)  (Sixth Sense, Gladiator)                 0.6  ...      0.10         1.5       0.625000

[12 rows x 10 columns]

In [15]:
frequent_itemsets3 = apriori(data, min_support=0.4, use_colnames=True)
frequent_itemsets3

   support                           itemsets
0      0.6                      (Sixth Sense)
1      0.7                        (Gladiator)
2      0.6                          (Patriot)
3      0.5           (Sixth Sense, Gladiator)
4      0.4             (Sixth Sense, Patriot)
5      0.6               (Patriot, Gladiator)
6      0.4  (Sixth Sense, Gladiator, Patriot)

In [17]:
rules3 = association_rules(frequent_itemsets3, metric="lift", min_threshold=0.8)
rules3

                 antecedents               consequents  antecedent support  ...  leverage  conviction  zhangs_metric
0              (Sixth Sense)               (Gladiator)                 0.6  ...      0.08         1.8       0.400000
1                (Gladiator)             (Sixth Sense)                 0.7  ...      0.08         1.4       0.533333
2              (Sixth Sense)                 (Patriot)                 0.6  ...      0.04         1.2       0.250000
3                  (Patriot)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
4                  (Patriot)               (Gladiator)                 0.6  ...      0.18         inf       0.750000
5                (Gladiator)                 (Patriot)                 0.7  ...      0.18         2.8       1.000000
6   (Sixth Sense, Gladiator)                 (Patriot)                 0.5  ...      0.10         2.0       0.500000
7     (Sixth Sense, Patriot)               (Gladiator)                 0.4  ...      0.12         inf       0.500000
8       (Patriot, Gladiator)             (Sixth Sense)                 0.6  ...      0.04         1.2       0.250000
9              (Sixth Sense)      (Patriot, Gladiator)                 0.6  ...      0.04         1.2       0.250000
10               (Gladiator)    (Sixth Sense, Patriot)                 0.7  ...      0.12         1.4       1.000000
11                 (Patriot)  (Sixth Sense, Gladiator)                 0.6  ...      0.10         1.5       0.625000

[12 rows x 10 columns]